ignore:
    - "wargaming/wot_encyclopedia_tanks"
    - "wargaming/wot_encyclopedia_tankinfo"
    - "wargaming/wot_encyclopedia_tankengines"
    - "wargaming/wot_encyclopedia_tankturrets"
    - "wargaming/wot_encyclopedia_tankradios"
    - "wargaming/wot_encyclopedia_tankchassis"
    - "wargaming/wot_encyclopedia_tankguns"
    - "wargaming/wot_ratings_types"
    - "wargaming/wot_ratings_dates"
    - "wargaming/wot_ratings_accounts"
    - "wargaming/wot_ratings_neighbors"
    - "wargaming/wot_ratings_top"
    - "wargaming/wgn_clans_list"
    - "wargaming/wgn_clans_info"
    - "wargaming/wgn_clans_membersinfo"
    - "wargaming/wgn_clans_glossary"
    - "wargaming/wgn_clans_messageboard"
    - "wargaming/wgn_clans_memberhistory"
