on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

name: Testing
env:
    GO111MODULE: on

permissions:
    contents: read

jobs:
    test:
        permissions:
            actions: write  # for styfle/cancel-workflow-action to cancel/stop running workflows
            contents: read  # for actions/checkout to fetch code
        strategy:
            matrix:
                go-version: [1.x, 1.17.x]
                platform: [ubuntu-latest]
                include:
                    # include windows, but only with the latest Go version, since there
                    # is very little in the library that is platform specific
                    - go-version: 1.x
                      platform: windows-latest

                    # only update test coverage stats with the most recent go version on linux
                    - go-version: 1.x
                      platform: ubuntu-latest
                      update-coverage: true
        runs-on: ${{ matrix.platform }}

        steps:
            - name: Cancel previous workflows
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                  access_token: ${{ github.token }}

            - uses: actions/setup-go@v3
              with:
                  go-version: ${{ matrix.go-version }}
            - uses: actions/checkout@v3

            - name: Run go test
              run: go test -v -race -coverprofile coverage.txt -covermode atomic ./...

            - name: Upload coverage to Codecov
              if: ${{ matrix.update-coverage }}
              uses: codecov/codecov-action@v3.1.0
